model:
  name: 'resnet50'
  pretrained: True
  load_weights: '/home/jtyo/Repos/PerformancePhotoRepos/performancereidTrainLITE/performancereidTrainLITE/train/weights/resnet50_duke_xent.pth.tar'
  resume: ''

data:
  sources: ['performancephoto']
  targets: ['performancephoto']
  save_dir: 'log/resnet50_duke'
  use_metric_cuhk03: True
  transforms: ['random_flip', 'color_jitter', 'random_crop']

performance:
  endpoint: ''
  username: ''
  password: ''
  database_name: ''
  aws_access_key_id: ''
  aws_secret_access_key: ''
  region_name: ''
  s3_bucket: ''

train:
  wandb_config: 'wandb_config.yaml'
  max_epoch: 250
  batch_size: 75
  lr: 0.0003
  lr_scheduler: 'cosine'
  seed: 4

test:
  batch_size: 6
  eval_freq: 4
  evaluate: False
  ranks: [1, 5, 10]
  visrank: False
  visrank_topk: 10

loss:
  name: 'triplet'
